{% set name = "submitit" %}
{% set version = "1.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7197b5f89789c8c66dcc5bb29a14083f9ed1e945e59db86685f1072059ba7d81

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - cloudpickle >=1.2.1
    - pip
    - python
    - typing_extensions >=3.7.4.2
  run:
    - cloudpickle >=1.2.1
    - python
    - typing_extensions >=3.7.4.2

test:
  imports:
    - submitit
    - submitit.auto
    - submitit.core
    - submitit.local
    - submitit.slurm

about:
  home: https://github.com/facebookincubator/submitit
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python 3.6+ toolbox for submitting jobs to Slurm
  doc_url: https://github.com/facebookincubator/submitit

extra:
  recipe-maintainers:
    - rpanai
